name: Check Version Tag

on:
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check package version
        run: |
          VERSION=$(grep "version" pyproject.toml | cut -d'"' -f 2)
          pip index versions google-surfer | grep $VERSION
          if [ $? -eq 0 ]; then
              echo "New version $VERSION is permitted."
          else
              echo "Version $VERSION already exists."
              exit 1
          fi
