name: Check Version Tag

on:
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check package version
        run: |
          VERSION=$(grep "version" pyproject.toml | cut -d'"' -f 2)
          pip index versions google-surfer | grep $VERSION
          if pip index versions google-surfer | grep $VERSION; then 
            echo "Version $VERSION already exists."
            exit 1
          else
            echo "New version $VERSION is permitted."
          fi
